# -*- coding: utf-8 -*-
"""Actividad 2 test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iULxw9g599LWYFybThyjfmAJf0m20H-5
"""

import array
import unittest
import doctest

#Cristian David Barragan 20211005074

class Matrix:

    """
    Clase que representa una matriz.

        Ejemplos:
    >>> matrix = Matrix(2, 3, [[1, 2, 3], [4, 5, 6]])
    >>> print(matrix)
    1   2   3
    4   5   6

    >>> print(matrix.cambio(0, 1))
    4   5   6
    1   2   3

    >>> print(matrix.multiplica(1, 2))
    4   5   6
    2   4   6

    >>> print(matrix.multiplo(0, 1, 3))
    10   17   24
    2   4   6
    """

    def __init__(self, rows, cols, elements=None):
        self.rows = rows
        self.cols = cols
        self.elements = array.array('i', [0] * (rows * cols)) if elements is None else array.array('i', [element for row in elements for element in row])

    def __str__(self):
        return '\n'.join(['   '.join(map(str, self.elements[i:i+self.cols])) for i in range(0, len(self.elements), self.cols)])

    def __getitem__(self, index):
        i, j = index
        return self.elements[i * self.cols + j]

    def __add__(self, other):
        if self.rows != other.rows or self.cols != other.cols:
            raise ValueError("Las matrices deben tener las mismas dimensiones para la suma.")
        result = Matrix(self.rows, self.cols)
        result.elements = array.array('i', [a + b for a, b in zip(self.elements, other.elements)])
        return result

    def __mul__(self, scalar):
        result = Matrix(self.rows, self.cols)
        result.elements = array.array('i', [element * scalar for element in self.elements])
        return result

    def tolist(self):
        return [self.elements[i:i + self.cols].tolist() for i in range(0, len(self.elements), self.cols)]


    def multiply(self, other):
        if self.cols != other.rows:
            raise ValueError("El número de columnas de la primera matriz debe ser igual al número de filas de la segunda.")
        result = Matrix(self.rows, other.cols)
        for i in range(self.rows):
            for j in range(other.cols):
                result.elements[i * result.cols + j] = sum(self.elements[i * self.cols + k] * other.elements[k * other.cols + j] for k in range(self.cols))
        return result

    def cambio(self, i, j):
        #Intercambia las filas i y j en la matriz
        temp = array.array('i', self.elements[j * self.cols: j * self.cols + self.cols])
        for k in range(self.cols):
            self.elements[j * self.cols + k] = self.elements[i * self.cols + k]
            self.elements[i * self.cols + k] = temp[k]

    def multiplica(self, i, b):
        #Multiplica la fila i por la constante b en la matriz
        for k in range(i * self.cols, i * self.cols + self.cols):
            self.elements[k] *= b

    def multiplo(self, i, j, a):
       # Agrega a la fila i la fila j multiplicada por a en la matriz
        for k in range(self.cols):
            self.elements[i * self.cols + k] += self.elements[j * self.cols + k] * a


class TestMatrixMethods(unittest.TestCase):
    def test_matrix_initialization(self):
        matrix = Matrix(2, 3, [[1, 2, 3], [4, 5, 6]])
        self.assertEqual(matrix.rows, 2)
        self.assertEqual(matrix.cols, 3)
        self.assertEqual(matrix.tolist(), [[1, 2, 3], [4, 5, 6]])

    def test_matrix_addition(self):
        matrix_a = Matrix(2, 3, [[1, 2, 3], [4, 5, 6]])
        matrix_b = Matrix(2, 3, [[7, 8, 9], [10, 11, 12]])
        result = matrix_a + matrix_b
        self.assertEqual(result.tolist(), [[8, 10, 12], [14, 16, 18]])

    def test_scalar_multiplication(self):
        matrix = Matrix(2, 3, [[1, 2, 3], [4, 5, 6]])
        result = matrix * 2
        self.assertEqual(result.tolist(), [[2, 4, 6], [8, 10, 12]])

    def test_matrix_multiplication(self):
        matrix_a = Matrix(2, 3, [[1, 2, 3], [4, 5, 6]])
        matrix_b = Matrix(3, 2, [[7, 8], [9, 10], [11, 12]])
        result = matrix_a.multiply(matrix_b)
        self.assertEqual(result.tolist(), [[58, 64], [139, 154]])

    def test_cambio(self):
        matrix = Matrix(2, 4, [[4, 5, 6, 9], [1, 10, 5, 9]])
        matrix.cambio(0, 1)
        self.assertEqual(matrix.tolist(), [[1, 10, 5, 9], [4, 5, 6, 9]])

    def test_multiplica(self):
        matrix = Matrix(2, 4, [[4, 5, 6, 9], [1, 10, 5, 9]])
        matrix.multiplica(1, 2)
        self.assertEqual(matrix.tolist(), [[4, 5, 6, 9], [2, 20, 10, 18]])

    def test_multiplo(self):
        matrix = Matrix(2, 4, [[4, 5, 6, 9], [1, 10, 5, 9]])
        matrix.multiplo(0, 1, 3)
        self.assertEqual(matrix.tolist(), [[7, 35, 21, 36], [1, 10, 5, 9]])


if __name__ == '__main__':
    unittest.main()
    #doctest.testmod()
    pass